disableKinds:
- sitemap
- taxonomy
- term
outputs:
  home:
  - html
caches:
  getresource:
    maxAge: 0
publishDir: generated_content
module:
  mounts:
  - source: layouts
    target: layouts
  - source: transformers
    target: layouts/partials/transformers
  imports:
  - path: github.com/theNewDynamic/tnd-content-generator
params:
  tnd_data_gen:
    format: yaml
    collections:
      - name: profiles
        limit: 30
        content:
          min: 1
          max: 1
          blocks: 
          - paragraph
      - name: posts
        transformer: ananke
        title: words
        limit: 300
        # transformer: bookshop
        content:
          min: 1
          max: 1
        blocks:
          min: 1
          max: 5
      - name: products
        limit: 1000