baseURL: "http://example.org/"
title: "Ananke Sandbox"
DefaultContentLanguage: en
disqusShortname: something
theme:
  - github.com/theNewDynamic/gohugo-theme-ananke
taxonomies:
  technology: technologies
cascade:
  featured_image: 