mounts:
- source: content/en
  target: content
  lang: en
- source: content/fr
  target: content
  lang: fr
- source: content/ja
  target: content
  lang: ja
- source: generator/generated_content/content/posts
  target: content/post
  lang: en
- source: generator/generated_content/content/products
  target: content/products
  lang: en
- source: static
  target: static
- source: generator/generated_content/images
  target: static/images